log_format json escape=json '{ "time": "$time_iso8601", '
                            '"remote_addr": "$remote_addr", '
                            '"remote_user": "$remote_user", '
                            '"ssl_protocol_cipher": "$ssl_protocol/$ssl_cipher", '
                            '"body_bytes_sent": "$body_bytes_sent", '
                            '"request_time": "$request_time", '
                            '"status": "$status", '
                            '"request": "$request", '
                            '"request_method": "$request_method", '
                            '"http_referrer": "$http_referer", '
                            '"http_x_forwarded_for": "$http_x_forwarded_for", '
                            '"http_cf_ray": "$http_cf_ray", '
                            '"host": "$host", '
                            '"server_name": "$server_name", '
                            '"upstream_address": "$upstream_addr", '
                            '"upstream_status": "$upstream_status", '
                            '"upstream_response_time": "$upstream_response_time", '
                            '"upstream_response_length": "$upstream_response_length", '
                            '"upstream_cache_status": "$upstream_cache_status", '
                            '"http_user_agent": "$http_user_agent" }';

log_format main   '{"@timestamp":"$time_iso8601",'
                        '"@source":"$server_addr",'
                        '"hostname":"$hostname",'
                        '"ip":"$http_x_forwarded_for",'
                        '"client":"$remote_addr",'
                        '"request_method":"$request_method",'
                        '"scheme":"$scheme",'
                        '"domain":"$server_name",'
                        '"referer":"$http_referer",'
                        '"request":"$request_uri",'
                        '"args":"$args",'
                        '"size":$body_bytes_sent,'
                        '"status": $status,'
                        '"responsetime":$request_time,'
                        '"upstreamtime":"$upstream_response_time",'
                        '"upstreamaddr":"$upstream_addr",'
                        '"http_user_agent":"$http_user_agent",'
                        '"https":"$https"'
                        '}';

log_format default  '[$time_local], '
                    '$remote_addr  $remote_user, '
                    '"SNI": "$server_name", '
                    '"Resquest": "$request", '
                    '"$server_port", '
                    '"Status": "$status", '
                    '"Responsetime":$request_time, '
                    '"Referer: "$http_referer", '
                    '"$http_x_forwarded_for", '
                    '"Upstreamtime": "$upstream_response_time", '
                    '"Upstreamaddr": "$upstream_addr", '
                    '"Upstream_status": "$upstream_status" ';

# Logging Settings
access_log /var/log/nginx/access.log default;
error_log /var/log/nginx/error.log notice;