- name: Setup and Update Config Docker  Nodes
  hosts: web
  become: True
  collections:
    - Community.Docker
  vars:
    container_count: 1
    default_container_name: nginxhost
    default_container_image: stenote/nginx-hostname

  tasks:

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: disabled
        policy: allow

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
   
    - name: install dependency
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - gnupg

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        validate_certs: false

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        state: present
        exposed_ports:
          - "80:80"
        recreate: true
      with_sequence: count={{ container_count }}

    - apt:
        update_cache: yes
        state: latest
        name: python3-pip

    - pip:
        name: docker


    ##### setup group and user
    - name: create docker group
      become: true
      group:
        name: docker
        state: present

    - name: add user to group 
      become: true
      user:
        name: "{{ansible_user}}"
        groups: docker
        append: true

    - meta: reset_connection  